export interface AuctionProduct {
  id: number;
  image: string;
  alt: string;
  title: string;
  bid: string;
  category?: string;
  timeLeft?: string;
  currentBid?: number;
  bidders?: number;
  description: string;
}

export const AUCTION_PRODUCTS: AuctionProduct[] = [
  {
    id: 1,
    image: '/airpod.jpg',
    alt: 'Wireless Airbuds auction',
    title: 'Wireless Airbuds',
    bid: 'Starting bid: 59ETB',
    category: 'Electronics',
    timeLeft: '2h 30m',
    currentBid: 59,
    bidders: 12,
    description: 'Comfortable wireless earbuds with long battery life and clear sound for music and calls.',
  },
  {
    id: 2,
    image: '/iphone.jpg',
    alt: 'iPhone auction',
    title: 'Smartphone',
    bid: 'Starting bid: 199ETB',
    category: 'Electronics',
    timeLeft: '5h 15m',
    currentBid: 199,
    bidders: 8,
    description: 'A sleek smartphone with a vibrant display, fast processor, and durable glass design.',
  },
  {
    id: 3,
    image: '/mac.jpg',
    alt: 'Mac auction',
    title: 'Notebook',
    bid: 'Starting bid: 499ETB',
    category: 'Electronics',
    timeLeft: '1d 4h',
    currentBid: 499,
    bidders: 5,
    description: 'Lightweight notebook built for productivity, featuring a responsive keyboard and long battery life.',
  },
  {
    id: 4,
    image: '/ps5.jpg',
    alt: 'PS5 auction',
    title: 'Gaming Console',
    bid: 'Starting bid: 299ETB',
    category: 'Gaming',
    timeLeft: '3h 45m',
    currentBid: 299,
    bidders: 3,
    description: 'Next-gen console offering immersive gaming, fast loading, and stunning graphics.',
  },
  {
    id: 5,
    image: '/speaker.jpg',
    alt: 'AXESS Speaker auction',
    title: 'Wireless Speaker',
    bid: 'Starting bid: 149ETB',
    category: 'Electronics',
    timeLeft: '12h 20m',
    currentBid: 149,
    bidders: 7,
    description: 'Portable Bluetooth speaker with powerful bass and a compact design for anywhere listening.',
  },
  {
    id: 6,
    image: '/black.jpg',
    alt: 'Black auction',
    title: 'Airpods',
    bid: 'Starting bid: 299ETB',
    category: 'Electronics',
    timeLeft: '2d 8h',
    currentBid: 299,
    bidders: 5,
    description: 'Premium noise-cancelling wireless earbuds with a comfortable fit and fast charging.',
  },
  {
    id: 7,
    image: '/chair.jpg',
    alt: 'Chair auction',
    title: 'Gaming Chair',
    bid: 'Starting bid: 199ETB',
    category: 'Furniture',
    timeLeft: '1d 6h',
    currentBid: 199,
    bidders: 4,
    description: 'Ergonomic gaming chair with adjustable height and lumbar support for long sessions.',
  },
  {
    id: 8,
    image: '/oven.jpg',
    alt: 'Oven auction',
    title: 'Electric Oven',
    bid: 'Starting bid: 299ETB',
    category: 'Appliances',
    timeLeft: '4h 30m',
    currentBid: 299,
    bidders: 6,
    description: 'High-performance electric oven with multiple cooking modes and easy-clean features.',
  },
  {
    id: 9,
    image: '/keyboard.jpg',
    alt: 'Keyboard auction',
    title: 'Gaming Keyboard',
    bid: 'Starting bid: 99ETB',
    category: 'Electronics',
    timeLeft: '6h 45m',
    currentBid: 99,
    bidders: 9,
    description: 'Mechanical keyboard with RGB lighting and responsive switches for fast gameplay.',
  },
  {
    id: 10,
    image: '/fans.jpg',
    alt: 'Fans auction',
    title: 'Home Fans',
    bid: 'Starting bid: 49ETB',
    category: 'Appliances',
    timeLeft: '3h 20m',
    currentBid: 49,
    bidders: 11,
    description: 'Quiet and energy-efficient home fans designed to keep rooms cool and comfortable.',
  },
  {
    id: 11,
    image: '/TCL40.jpg',
    alt: 'TCL40 auction',
    title: '40-inch Smart TV',
    bid: 'Starting bid: 299ETB',
    category: 'Electronics',
    timeLeft: '1d 12h',
    currentBid: 299,
    bidders: 2,
    description: 'A smart TV with crisp display, streaming apps built in, and easy connectivity options.',
  },
  {
    id: 12,
    image: '/iron.jpg',
    alt: 'Iron auction',
    title: 'Electric Iron',
    bid: 'Starting bid: 299ETB',
    category: 'Appliances',
    timeLeft: '2h 15m',
    currentBid: 299,
    bidders: 10,
    description: 'Fast-heating electric iron with smooth glide plates and anti-drip performance.',
  },
  {
    id: 13,
    image: '/powerbanker.jpg',
    alt: 'Powerbanker auction',
    title: 'Portable Power Bank',
    bid: 'Starting bid: 99ETB',
    category: 'Electronics',
    timeLeft: '8h 30m',
    currentBid: 99,
    bidders: 15,
    description: 'Compact power bank that delivers several full charges and supports fast USB charging.',
  },
  {
    id: 14,
    image: '/sonybluetooth.jpg',
    alt: 'Sony Bluetooth auction',
    title: 'Wireless Bluetooth Speaker',
    bid: 'Starting bid: 149ETB',
    category: 'Electronics',
    timeLeft: '5h 45m',
    currentBid: 149,
    bidders: 6,
    description: 'Portable speaker offering premium sound quality and wireless connectivity for parties.',
  },
  {
    id: 15,
    image: '/smartwatch.jpg',
    alt: 'Smartwatch auction',
    title: 'Smartwatch',
    bid: 'Starting bid: 199ETB',
    category: 'Electronics',
    timeLeft: '4h 10m',
    currentBid: 199,
    bidders: 8,
    description: 'Stylish smartwatch with health tracking, notifications, and long battery life.',
  },
  {
    id: 16,
    image: '/sonicheadphone.jpg',
    alt: 'Sonic Headphone auction',
    title: 'Wireless Headphones',
    bid: 'Starting bid: 199ETB',
    category: 'Electronics',
    timeLeft: '7h 25m',
    currentBid: 199,
    bidders: 5,
    description: 'Comfortable over-ear headphones with crisp audio and wireless freedom.',
  },
];
